dist: xenial
sudo: false
language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: pypy3.5-6.0
cache:
  - pip
install:
  - pip install tox-travis
script:
  - tox
