sudo: false
language: python
matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    # Travis' PyPy3 version is way too old. Unfortunately we have to set up our own
    - python: pypy3
      env: PYENV_VERSION=pypy3-portable-5.7.0
cache:
  - pip
before_install:
  - |
    if [ -n "$PYENV_VERSION" ]; then
      set -ex

      export PYENV_ROOT="$HOME/.pyenv"
      git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"

      [ -z "$VIRTUAL_ENV" ] || deactivate
      export PATH="$PYENV_ROOT/bin:$PATH"
      pyenv install "$PYENV_VERSION"
      eval "$(pyenv init -)"
      pyenv global "$PYENV_VERSION"

      pip install -U virtualenv
      export VIRTUAL_ENV="$HOME/virtualenv/$PYENV_VERSION"
      virtualenv "$VIRTUAL_ENV"
      source "$VIRTUAL_ENV/bin/activate"

      set +ex
    fi
install:
  - pip install tox-travis
script:
  - tox
